name: Reusable Release
on:
  workflow_call:
    inputs:
      nightly:
        type: boolean
        required: false
        default: false
        description: "Run nightly release"

env:
  GH_USER: asafhirschfeld
  AQUA_DOCKERHUB_REPO: asafhirschfeld

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml

  release:
    runs-on: ubuntu-latest
    # needs: integration-tests
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create bundle
        run: make create-bundle

      - name: setup-oras
        uses: oras-project/setup-oras@v1.2.2

      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER || env.GH_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image tags
        id: prepare-tags
        run: |
          if [ "${{ inputs.nightly }}" == "true" ]; then
             tags=("nightly")
           else
             RELEASE_VERSION=${GITHUB_REF/refs\/tags\/v/}
             MINOR_VERSION=$(echo $RELEASE_VERSION | cut -d. -f1,2)
             MAJOR_VERSION=$(echo $RELEASE_VERSION | cut -d. -f1)
             tags=("latest" "$RELEASE_VERSION" "$MINOR_VERSION" "$MAJOR_VERSION")
           fi
           echo "tags=${tags[*]}" >> $GITHUB_OUTPUT

      - name: Deploy policy bundle to ghcr.io (for backwards compatibility)
        if: ${{ inputs.nightly != true }}
        run: |
          tags=(${{ steps.prepare-tags.outputs.tags }})
          for tag in ${tags[@]}; do
              echo "Pushing artifact with tag: ${tag}"
              oras push ghcr.io/${{ github.event.repository.owner.name }}/trivy-policies:${tag} \
              --artifact-type application/vnd.cncf.openpolicyagent.config.v1+json \
              --annotation "org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
              --annotation "org.opencontainers.image.revision=$GITHUB_SHA" \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip
          done

      - name: Deploy checks bundle to registries
        run: |
          tags=(${{ steps.prepare-tags.outputs.tags }})
          registries=(
            "ghcr.io/asafhirschfeld/trivy-checks-more"
          )
          for registry in ${registries[@]}; do
            for tag in ${tags[@]}; do
              echo "Pushing artifact to ${registry}:${tag}"
              if oras push -v ${registry}:${tag} \
              --artifact-type application/vnd.cncf.openpolicyagent.config.v1+json \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip; then
                echo "Successfully pushed artifact to ${registry}:${tag}"
              else
                echo "Failed to push artifact to ${registry}:${tag}"
                exit 1
              fi
            done
          done
